# Manually trigger to create a new release branch with bumped build version
name: Create Build Release Branch

on:
  workflow_dispatch:

jobs:
  create-release:
    uses: ./.github/workflows/create-release-branch-template.yml
    with:
      versionBump: bump-build
    secrets: inherit
