# Manually trigger to create a new release branch with bumped minor version
name: Create Minor Release Branch

on:
  workflow_dispatch:

jobs:
  create-release:
    uses: ./.github/workflows/create-release-branch-template.yml
    with:
      versionBump: bump-minor
    secrets: inherit
